# Generated by Django 4.0.1 on 2022-10-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('poster_path', models.CharField(max_length=500)),
                ('language', models.CharField(max_length=250)),
                ('overview', models.TextField()),
                ('release_date', models.DateField()),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
